# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4308eaca0bf08e8e8eb41d5ca321f12bddfeb34730c0655adcd2eef0802d47f2682cf7c6ee121c101317e9aac75ea3052789c63fa2017f3c8781e8346aaf66d0

test:
  secret_key_base: f2adfea33e2b16ed3bc18acc05bc2ccd107f6e521a8c07a8bf7a9032a9eee80d5ae246feba8df5c4c61d0f50b73e04963d82b20ad502860af11236459bddf179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
